"Implement possible moves of the bishop"
KlaraGajaszek/CC2020Chess pull request #40
Opened 2021-01-27 19:31 UTC by sebslon

Ruchy dla gońca, z biciem przeciwnych pionków.
- Zmieniłem właściwość "side" poszczególnych pionków na readonly (jeżeli dobrze pamiętam to na daily o tym rozmawialiśmy),
- Otypowałem metodę findLegalMoves,

Proszę o CR

2021-01-29 23:03 UTC, KlaraGajaszek requested changes

2021-01-29 23:03 UTC, KlaraGajaszek commented on src/pieces/bishop/bishop.ts
> +    for (let i = 1; this.x - i >= 0 && this.y + i <= 7; i++) {
zamiast komentarzy użyj proszę zamiast i  kolejno u jako up, d jako down, r jako rigth i l jako left

2021-01-29 23:03 UTC, KlaraGajaszek commented on src/board.ts
> +
usuń tą pustą linijke

2021-01-29 23:03 UTC, KlaraGajaszek commented on src/board.ts
Możesz  zobazczyc jak w  PR u Szymona zrobiłam implementację trochę inaczej to rozłożyłam, ale ogólnie jest ok jak nie będziesz chciał tego  przerabiać według tamtego algorytmu to zostaw

2021-01-29 23:03 UTC, KlaraGajaszek commented on src/pieces/bishop/bishop.ts
> +import { Field } from '../../types'
Na planszy nie pojawiająsię pionki prawdopodobnie będziesz musiał zmienić tąliniję  którą podrzuciłam na discordzie

2021-01-30 18:01 UTC, sebslon commented
Hej, wrzuciłem sugerowaną poprawkę do nazewnictwa w pętlach, z resztą sie powstrzymałem ponieważ Rafał wrzucił refactor i stwierdziłem, że ewentualne poprawki w bishopie zrobię jak ustalimy co z resztą kodu

2021-01-31 14:34 UTC, maciekkwiet reviewed
Jak dla mnie wygląda wszystko dobrze. Jednak chciałbym może żeby Rafała PR poszła jako pierwsza a później przerobilibyśmy to w sposób taki żeby kod był już zrobiony i poprawiony do nowej wersji

2021-01-31 14:34 UTC, maciekkwiet commented on src/pieces/pawn.ts
> +    console.log(possibleMoves)
Do usunięcia

2021-01-31 20:58 UTC, KlaraGajaszek approved these changes
Rozwiąż  konflikty i mergujemy

2021-02-01 20:22 UTC, sebslon commented
- Kod do poprawy, poprawię jak finalnie skończymy refactoring :)

2021-02-04 21:16 UTC, maciekkwiet approved these changes

2021-02-04 21:20 UTC, maciekkwiet commented on src/pieces/pawn.ts
> +    console.log(possibleMoves)
Usuńmy to jeszcze

2021-02-05 11:10 UTC, KlaraGajaszek approved these changes

2021-02-05 16:50 UTC, merged