Knight moves
KlaraGajaszek/CC2020Chess pull request #42
Opened 2021-01-28 18:01 UTC by wojaneta

closes #34

2021-01-29 23:22 UTC, KlaraGajaszek requested changes
Hej odemnie uwaga do całości jak coś by było nie jasne to pisz to  się jakoś po południu zdzwonimy i spróbujemy napisać to razem :)

2021-01-29 23:22 UTC, KlaraGajaszek commented on src/board.ts
Możemy ten kod trochę zmodyfikować żeby był wydajniejszy
1. Zauważ że koń ma ściśle zdefiniowane możliwości  ruchu 
Dlatego możemy zdefiniować wszystkoemożliwości  dla niego 

const moves = [[2, 1], [1, 2], [-2, 1], [1, -2], [-2, -1], [2, -1], [-1, 2], [-1, -2]];
następnie tworzymy jakgo nowe pozycje jako
 let newX = 0;
        let newY = 0;
        const attackMoves = [];
2. Następnie tworzymy możliwości ruchu dla konia

  for (const subTab of moves) {
            newX = this.x + subTab[0];
            newY = this.y + subTab[1];
            if (newX <= 7 && newX >= 0 && newY <= 7 && newY >= 0) {
                if (gameArea[newX][newY]) {
                    if (gameArea[newX][newY].side !== this.side || gameArea[newX][newY].side == this.side)
                        attackMoves.push(`${newX},${newY}`);
                } else attackMoves.push(`${newX},${newY}`);
            }
        }
NA koniec zwracamy naszą tablicę ruchów   return attackMoves i to wszytsko  oplatamy funkcją findAttackingMoves

Następniw tworzymy funkcję z wszystkimi możliwymi  ruchami w której występuje też attackingMoves, bo ruch atakujący też tak jakby zawiera się w możliwych ruchcach dlatego  wywołujemy ja w findLegalMoves lub possibleMoves nazwiesz jak będziesz chciała

    findLegalMoves(gameArea:Field[][]):string {
        let attack = this.findAttackingMoves(gameArea);
        let legal = [];

        for (const move of attack) {
            const attackX = move[0];
            const attackY = move[2];
            if (!gameArea[attackX][attackY] || gameArea[attackX][attackY].side !== this.side) {
                legal.push(move);
            }
     
        }

        return legal;
    }

2021-01-31 14:40 UTC, maciekkwiet approved these changes
Wygląda chyba okey, przyznam się że sprawdziłem tylko kod, ale poczekajmy z mergem tego do merga Rafała z refactoringiem, żebyśmy później nie musieli tego poprawiać drugi raz gdyby była taka konieczność :D

2021-01-31 14:40 UTC, maciekkwiet commented on src/pieces/knight.ts
> +        const possibleMoves: Array<string> = [];
Częściej używa się string[]

2021-01-31 20:57 UTC, KlaraGajaszek approved these changes
Rozwiąż konfilkty i  mergujemy :)

2021-02-02 18:41 UTC, merged