Add queen moves
KlaraGajaszek/CC2020Chess pull request #43
Opened 2021-01-29 12:33 UTC by WarmuzWojtek

closes #32

2021-01-30 17:00 UTC, KlaraGajaszek requested changes
Podeszla bym do tego trochę inaczej. Najlepiej rozrysować sb na kartce wymyśleć algorytm i go powtarzać zmieniając sane. Daj znać co myślisz o  tym podejściu

1. Stworzyłabym funkcję  findAttackingMoves(board)={.......}
2. W tej funkcji stworzyłabym tablicę  const attackingMoves = [];
3. Następnie w tej funkcji zdefiniowałabym  możliwości ruchów
 let leftUp = this.x <= this.y ? this.x : this.y;
        let leftDown = 7 - this.y <= this.x ? 7 - this.y : this.x;
        let rightUp = this.y <= 7 - this.x ? this.y : 7 - this.x;
        let rightDown = 7 - this.y <= 7 - this.x ? 7 - this.y : 7 - this.x;
4. I potem w tej  funkcji napisała "algorytm" do wsyztskich posunięć:

        for (let lu = 1; lu <= leftUp; lu++) {
            if (board[this.x - lu][this.y - lu]) {
                attackingMoves.push(`${this.x - lu},${this.y - lu}`);
                break;
            }
            leftUp > 0 && attackingMoves.push(`${this.x - lu},${this.y - lu}`);
        }

        for (let ld = 1; ld <= leftDown; ld++) {
            if (board[this.x - ld][this.y + ld]) {
                attackingMoves.push(`${this.x - ld},${this.y + ld}`);
                break;
            }
            leftDown > 0 && attackingMoves.push(`${this.x - ld},${this.y + ld}`);
        }

itd. potem musisz jeszcze napisać funkcje w któych rozważysz  rd, ru, samo u, samo d, samo l, samo r r(literki  oznaczają nazwy kierunków poruszania)

Jak już to napiszesz to składasz funkcję findLegalMoves w któej  tworzysz pustą tablicę  
1. const attack = [] 
2. następnie wywołujesz findAttackingMoves(board) i przypisujesz ją do danego parametry np. attackFiles = findAttackingMoves(board) 
3. Potem w tej funkcji tworzysz  fora  (let i = 0; i < attackFiles .length; i++) {
w którym zczytujesz poszczególne wartości  w zależności od indexu iteracji 
4. const tab = param[i];
5. i robisz zwykłego ifa 

            if (board[tab[0]][tab[2]]) {
                if (board[tab[0]][tab[2]].side == this.side) {
                    attack.push(param[i]);
                }
            }
}

To jest jedno z przykładowych rozwiwązań ale wydaje mi sisę czytelniejsze i bardziej optymalne. Daj znać co myślisz ?

2021-01-30 17:00 UTC, KlaraGajaszek commented on src/pieces/queen.ts
>  class Queen extends Piece {
Brakuje nam jeszcze czarnego pionka

2021-01-31 14:43 UTC, maciekkwiet requested changes

2021-01-31 14:43 UTC, maciekkwiet commented on src/board.ts
> +let queen = new Queen(7, 3, 'white')
Dodajmy też królową dla czarnych

2021-01-31 14:43 UTC, maciekkwiet commented on src/pieces/queen.ts
> +            if (board[this.x][this.y + i] && board[this.x][this.y + i]?.side !== this.side) {
Attacking moves nie jest zależne od koloru. Chcemy równiez mieć możliwośc w tej funkcji takiej że król nie może zbić przeciwnika jeżeli jest jakby "chroniony" przez inną funkcję

2021-02-03 18:16 UTC, maciekkwiet approved these changes
Mała drobna zmina i bedzie pley :D

2021-02-03 18:16 UTC, maciekkwiet commented on src/pieces/queen.ts
> +            } else {
Ten else nie jest potrzebny, możemy zrobić dwa ify i to będzie lepsze rozwiazanie

2021-02-03 18:16 UTC, maciekkwiet commented on src/pieces/queen.ts
> +            }
W idealnym układzie możemy użyc funkcji filter na tablicy ale to jako zadanie z gwiazdką niewymagane :D

2021-02-04 10:53 UTC, merged