Rook movement
KlaraGajaszek/CC2020Chess pull request #44
Opened 2021-01-29 18:59 UTC by szymonsuchanowski

closes #33

2021-01-29 22:12 UTC, KlaraGajaszek requested changes
Pozmieniałam trochę  kod daj znać co  o tym myślisz ?

2021-01-29 22:12 UTC, KlaraGajaszek commented on src/pieces/rook.ts
> +    const possibleMoves: Array<string> = [];
zamiast wszedzie pisać i yżyj w pętlach 
u - jakoup
d- jako down
r- right
l- jako  left wtedy kod się lepiej czyta :)

2021-01-29 22:12 UTC, KlaraGajaszek commented on src/pieces/rook.ts
> +      } else break;
nie podoba mi sie zapis else break zamiast tego możemy troche inaczej skonstruowac kod ponizej napisze  mój  pomysł

2021-02-01 22:32 UTC, maciekkwiet commented
Pamietaj żeby rozwiązać konflikty przed "oddaniem" do reviev, bo możliwe że będzie trzeba troche cos w kodzie po rozwiazaniu konfliktow zmienic :D

2021-02-03 19:46 UTC, szymonsuchanowski commented
zmienione zgodnie z tym co omawialiśmy na daily :)

2021-02-03 22:07 UTC, szymonsuchanowski commented
powinno być ok, jak jeszcze coś można lepiej rozwiązać, to dawajcie znać :)

2021-02-03 22:37 UTC, maciekkwiet approved these changes
Jak dla mnie jest git!

2021-02-04 20:26 UTC, merged