Intro
KlaraGajaszek/CC2020Chess pull request #80
Opened 2021-02-14 12:38 UTC by WarmuzWojtek

2021-02-14 14:34 UTC, sebslon reviewed
Mi się wizualnie bardzo podoba :) 

Można by się pozbyć this.startGame.startGame(); z konstruktora Game jeśli by przypisać eventListenera w funkcji render od razu

2021-02-14 15:58 UTC, maciekkwiet commented on src/startScreen.ts
> +  }
Możemy to usunąć

2021-02-14 16:02 UTC, maciekkwiet requested changes
Jest super, ale może twie dwie małe propozycje ode mnie

2021-02-14 16:02 UTC, maciekkwiet commented on src/startScreen.ts
> +  public promoteRender() {
Te funkcje są z natury public wiec usunmy te public wszedzie

2021-02-14 16:02 UTC, maciekkwiet commented on src/startScreen.ts
> +  public startGame() {
Może z tej funkcji renderujmy new Game() po wcisnieciu start, a wywołanie tego możemy dać do main.ts

2021-02-14 16:04 UTC, maciekkwiet commented
Ogólnie bardzo mi sie podoba!
Zastanwiam się czy może nie warto już teraz zrobić np. przejscia do gry jakiesgos łagodniejszego(animacja), wtedy by to chyba jeszcze lepiej wyglądało :D

2021-02-15 11:54 UTC, wojaneta reviewed
Jak dla mnie wygląda super! Poprawiłabym tylko widok na mniejszych ekranach, bo  napis zasłania button play. Jakbyś potrzebował pomocy to dawaj znać.

2021-02-15 12:44 UTC, WarmuzWojtek commented
Wrzuciłem po poprawkach i tak:
zrobiłem:
- zrobiłem animację płynnego przejścia na playground,
- dorzuciłem parę rzeczy w css-ie playgroundu, żeby było bardziej spójnie z intro,
- dorzuciłem nazwy zegarów,
nie zrobiłem:
- zmian w strukturze, o którym pisał Maciek i Sebastian,
- RWD, o którym pisała Aneta,

zdecydowałem się to puścić tak, bo na więcej nie będę miał dziś czasu, a przynajmniej na prezentację wydaje mi się, że jest OK :)

2021-02-15 17:55 UTC, maciekkwiet commented
Tak jak w drugim PR dopiszmy "// TO DO" w miejscach które trzeba  bedzie zmienić i zmergujmy PR

2021-02-15 18:15 UTC, merged